set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN E3 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports debug]
set_property PACKAGE_PIN N17 [get_ports debug]

set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN C12 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports isClk]
set_property PACKAGE_PIN V10 [get_ports isClk]

set_property IOSTANDARD LVCMOS33 [get_ports {displayAddress[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {displayAddress[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {displayAddress[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {displayAddress[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {displayAddress[0]}]
set_property PACKAGE_PIN R17 [get_ports {displayAddress[4]}]
set_property PACKAGE_PIN R15 [get_ports {displayAddress[3]}]
set_property PACKAGE_PIN M13 [get_ports {displayAddress[2]}]
set_property PACKAGE_PIN L16 [get_ports {displayAddress[1]}]
set_property PACKAGE_PIN J15 [get_ports {displayAddress[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {displayController[1]}]
set_property PACKAGE_PIN U11 [get_ports {displayController[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {displayController[0]}]
set_property PACKAGE_PIN U12 [get_ports {displayController[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {leds[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]
set_property PACKAGE_PIN V11 [get_ports {leds[15]}]
set_property PACKAGE_PIN V12 [get_ports {leds[14]}]
set_property PACKAGE_PIN V14 [get_ports {leds[13]}]
set_property PACKAGE_PIN V15 [get_ports {leds[12]}]
set_property PACKAGE_PIN T16 [get_ports {leds[11]}]
set_property PACKAGE_PIN U14 [get_ports {leds[10]}]
set_property PACKAGE_PIN T15 [get_ports {leds[9]}]
set_property PACKAGE_PIN V16 [get_ports {leds[8]}]
set_property PACKAGE_PIN U16 [get_ports {leds[7]}]
set_property PACKAGE_PIN U17 [get_ports {leds[6]}]
set_property PACKAGE_PIN V17 [get_ports {leds[5]}]
set_property PACKAGE_PIN R18 [get_ports {leds[4]}]
set_property PACKAGE_PIN N14 [get_ports {leds[3]}]
set_property PACKAGE_PIN J13 [get_ports {leds[2]}]
set_property PACKAGE_PIN K15 [get_ports {leds[1]}]
set_property PACKAGE_PIN H17 [get_ports {leds[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {whichLight[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichLight[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichLight[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichLight[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichLight[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichLight[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichLight[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichLight[0]}]
set_property PACKAGE_PIN J17 [get_ports {whichLight[7]}]
set_property PACKAGE_PIN J18 [get_ports {whichLight[6]}]
set_property PACKAGE_PIN T9 [get_ports {whichLight[5]}]
set_property PACKAGE_PIN J14 [get_ports {whichLight[4]}]
set_property PACKAGE_PIN P14 [get_ports {whichLight[3]}]
set_property PACKAGE_PIN T14 [get_ports {whichLight[2]}]
set_property PACKAGE_PIN K2 [get_ports {whichLight[1]}]
set_property PACKAGE_PIN U13 [get_ports {whichLight[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {whichPipe[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichPipe[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichPipe[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichPipe[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichPipe[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichPipe[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichPipe[0]}]
set_property PACKAGE_PIN T10 [get_ports {whichPipe[6]}]
set_property PACKAGE_PIN R10 [get_ports {whichPipe[5]}]
set_property PACKAGE_PIN K16 [get_ports {whichPipe[4]}]
set_property PACKAGE_PIN K13 [get_ports {whichPipe[3]}]
set_property PACKAGE_PIN P15 [get_ports {whichPipe[2]}]
set_property PACKAGE_PIN T11 [get_ports {whichPipe[1]}]
set_property PACKAGE_PIN L18 [get_ports {whichPipe[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports dp]
set_property PACKAGE_PIN H15 [get_ports dp]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets debug]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets reset]
set_property SEVERITY {Warning} [get_drc_checks LUTLP-1]